apiVersion: v1
kind: Pod
metadata:
  name: encrypted-model-inference
  labels:
    app: vllm-encrypted-model
spec:
  initContainers:
  - name: model-downloader
    image: localhost:5001/encrypted-model-downloader:latest
    ports:
    - containerPort: 22
      name: ssh
    env:
    - name: PRIVATE_KEY_FILE
      value: "/shared/keys/private.key"
    - name: OCI_REGISTRY
      value: "kind-registry:5000"
    - name: MODEL_NAME
      value: "qwen/qwen3-0.6b"
    - name: MODEL_DIR
      value: "/shared/ramdisk"
    - name: USE_TLS
      value: "false"
    volumeMounts:
    - name: shared-ramdisk
      mountPath: /shared
    resources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "8Gi"
        cpu: "2000m"
  containers:
  - name: vllm-server
    image: quay.io/donhunte/vllm-cpu:latest
    args:
    - serve
    - --model=/shared/ramdisk/model
    - --served-model-name=encrypted-model
    - --max-model-len=10000
    ports:
    - containerPort: 8000
      name: http
    volumeMounts:
    - name: shared-ramdisk
      mountPath: /shared
      readOnly: true
    resources:
      requests:
        memory: "8Gi"
        cpu: "2000m"
        #nvidia.com/gpu: "1"
      limits:
        memory: "16Gi"
        cpu: "4000m"
        #nvidia.com/gpu: "1"
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 30
  volumes:
  - name: shared-ramdisk
    emptyDir:
      medium: Memory
      sizeLimit: "12Gi"
  restartPolicy: Never
